name: Update articles and deploy to Pages

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run fetcher
        run: python update_fetcher.py

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deploy
